# Generated by Django 3.1.1 on 2020-10-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=8)),
                ('twoauth', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
